### ISSUE TITLE
开源问题

### ISSUE THREAD

**Issue by CatOneTwo** [CupidJay/Tobias#1]

**Comment by CatOneTwo** [comment]
作者你好，请问代码什么时候开源呢

3.1 Object localization using a random CNN 生成的mask是二元的，这种 mask 怎么可视化才能得到图1的那种效果呢

**Comment by CupidJay** [comment]
Thanks for your interst. Our paper is still under review now and codes will be released within one month. For the figures in Fig. 1, you can directly use the activation value after summing over the depth channel (directly normalize this map to [0,1] and do not use thresholding).

**Comment by CatOneTwo** [comment]
Thanks! I will have a try~

**Comment by CupidJay** [comment]
Our code has been released now and I will close this issue.
