### ISSUE TITLE
Question about bbox of ImageNet

### ISSUE THREAD

**Issue by pprp** [CupidJay/Tobias#2]
https://github.com/CupidJay/Tobias/blob/f2f57d62bb50a73d9c411d7da96df4087a19e871/localization_code/ImageNet_SCDA.py#L174-L176

Hi, thank you for your great work. I wonder where is the bbox files of ImageNet.

Can you provide the bbox folder?

**Comment by CupidJay** [comment]
Thanks for your interest. The bbox annotations can be downloaded from the official website at [here](http://image-net.org/challenges/LSVRC/2012/).
